from enum import Enum


class State(str, Enum):
    GREETING = "GREETING"
    WAITING_SIMULATION_CONFIRM = "WAITING_SIMULATION_CONFIRM"
    WAITING_CPF = "WAITING_CPF"

    # Fluxo simulação
    RUNNING_SIMULATION = "RUNNING_SIMULATION"
    CONFIRM_SIMULATION = "CONFIRM_SIMULATION"
    WAITING_CUSTOM_INSTALLMENT = "WAITING_CUSTOM_INSTALLMENT"
    WAITING_CUSTOM_TERM = "WAITING_CUSTOM_TERM"

    # Fluxo proposta
    WAITING_ADDRESS_CEP = "WAITING_ADDRESS_CEP"
    WAITING_ADDRESS_STREET = "WAITING_ADDRESS_STREET"
    WAITING_ADDRESS_NUMBER = "WAITING_ADDRESS_NUMBER"
    WAITING_ADDRESS_NEIGHBORHOOD = "WAITING_ADDRESS_NEIGHBORHOOD"
    WAITING_ADDRESS_CITY = "WAITING_ADDRESS_CITY"
    WAITING_ADDRESS_STATE = "WAITING_ADDRESS_STATE"
    WAITING_RG = "WAITING_RG"
    WAITING_RG_DATE = "WAITING_RG_DATE"
    WAITING_PIX_KEY = "WAITING_PIX_KEY"
    WAITING_MARITAL_STATUS = "WAITING_MARITAL_STATUS"
    GENERATING_PROPOSAL = "GENERATING_PROPOSAL"
    PROPOSAL_SENT = "PROPOSAL_SENT"

    # Fluxo Facta (banco secundário)
    FACTA_WAITING_CONSENT = "FACTA_WAITING_CONSENT"
    FACTA_WAITING_PHONE = "FACTA_WAITING_PHONE"
    FACTA_WAITING_ALT_PHONE = "FACTA_WAITING_ALT_PHONE"
    FACTA_CONFIRM_SIMULATION = "FACTA_CONFIRM_SIMULATION"
    FACTA_WAITING_CUSTOM_INSTALLMENT = "FACTA_WAITING_CUSTOM_INSTALLMENT"
    FACTA_WAITING_CUSTOM_TERM = "FACTA_WAITING_CUSTOM_TERM"
    FACTA_WAITING_CEP = "FACTA_WAITING_CEP"
    FACTA_WAITING_PIX_KEY = "FACTA_WAITING_PIX_KEY"

    # Agendamento
    WAITING_SCHEDULE_TIME = "WAITING_SCHEDULE_TIME"
    SCHEDULED = "SCHEDULED"

    # Outros
    HUMAN_HANDOFF = "HUMAN_HANDOFF"
    ERROR = "ERROR"
